[FEAT/#16] week7 필수과제
DO-SOPT-ANDROID/youbin-lee pull request #17
Opened 2023-12-21 09:56 UTC by leeeyubin

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #16

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- [x] 합동세미나 전체 회고
- [x] 기존 LiveData를, UI에서 일어나는 다양한 이벤트와 상태에 대한 처리를 StateFlow 또는 SharedFlow를 통해 Handling하기

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/DO-SOPT-ANDROID/youbin-lee/assets/128459613/7e3a1efe-9e02-45ee-bef8-a0e666d8907c

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
- 로직 분리 조금 수정했습니다! 로그인 로직은 그대로 두고, 회원가입 로직은 불필요한 부분을 삭제해보았습니당

- 그리고 Flow를 사용해보았는데,,, 자신은 없네요,, 더 좋은 방법 있으면 조언 부탁드립니당

2023-12-21 11:09 UTC, Marchbreeze requested changes
코드가 점점 깔끔해지는게 보여서 좋아요 ㅎㅎ Flow observe 부분들은 모두 수정해주세요!

2023-12-21 11:09 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/auth/LoginActivity.kt
> +            loginViewModel.loginState.collect { loginState ->
Flow의 가장 큰 단점은, 액티비티나 프래그먼트의 생명주기를 알지 못한다는 점입니다! 그렇기 때문에, observe하는 과정에서 생명주기를 함께 알려주어야 메모리 누수를 막을 수 있어요.
flowWithLifecycle, repeatOnLifecycle 에 대해 알아보고 수정해주세요!

[https://hongbeomi.medium.com/%EB%B2%88%EC%97%AD-android-ui%EC%97%90%EC%84%9C-flow%EB%A5%BC-%EC%88%98%EC%A7%91%ED%95%98%EB%8A%94-%EC%95%88%EC%A0%84%ED%95%9C-%EA%B8%B8-bd8449e67ec3](url)

2023-12-21 11:09 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/presentation/main/followerlist/FollowerListFragment.kt
> +    private val binding : FragmentFollowerListBinding get() = requireNotNull(_binding)
예외처리 너무 좋아요 ~~~

2023-12-21 13:07 UTC, leeeyubin commented on app/src/main/java/org/sopt/dosopttemplate/presentation/auth/LoginActivity.kt
> +            loginViewModel.loginState.collect { loginState ->
수정했습니다!! (잘 됐겠죠,,?) 덕분에 한 번 더 생각해보고 코드를 짠 것 같네요,, 주의하겠습니당

2023-12-21 16:55 UTC, Marchbreeze approved these changes
빠른 수정 좋습니다 ~~~

2023-12-22 08:20 UTC, DoReMinWoo approved these changes
7주차 과제도 고생하셨습니다!~

2023-12-22 08:20 UTC, DoReMinWoo commented on app/src/main/java/org/sopt/dosopttemplate/util/UiState.kt
> +sealed interface UiState<out T> {
오홍 인터페이스를 미리 만들어두는게 좋네요~
과제할 때 잘 참고하겠습니다!

2023-12-22 08:20 UTC, DoReMinWoo commented on app/src/main/java/org/sopt/dosopttemplate/presentation/main/mypage/MyPageFragment.kt
> +        binding.run {
꼼꼼한 정렬 보기 너무 좋아요~

2023-12-22 08:20 UTC, DoReMinWoo commented on app/src/main/java/org/sopt/dosopttemplate/presentation/auth/SignUpViewModel.kt
> +            signUpId.value ?: "",
예외처리 좋네요!

2023-12-23 08:22 UTC, kangyuri1114 reviewed
야무진 코드 잘 봤어요 ~

2023-12-23 08:22 UTC, kangyuri1114 commented on app/src/main/java/org/sopt/dosopttemplate/presentation/auth/LoginActivity.kt
> +    private fun goToHomeActivity() {
함수화 해준거 좋네여~~~

2023-12-23 08:22 UTC, kangyuri1114 commented on app/src/main/java/org/sopt/dosopttemplate/presentation/auth/SignUpActivity.kt
> +                        shortToast(getString(R.string.ui_state_loading))
로딩 처럼 성공 실패도 스트링 해줘염 ><~

2023-12-26 03:12 UTC, merged